### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by snonux** [a-h/gemini#10]
Hi!

First, thanks for this Gemini server, I am using it for my personal Gemini capsule :-)

I was wondering how to configure the SNI. In the Awesome Gemini list (https://github.com/kr1sp1n/awesome-gemini) it states: "_a-h/gemini (Go) - Server for Linux, Mac, Raspberry Pi. Supports SNI for multiple domains on the same server, has Docker image._", is that actually correct?

But I could not find any docs about configuring SNI (server name indication so that multiple TLS certs/hosts can be used simultaneously) in a-h/gemini. For example, my capsule is served via buetow.org, but I would like to serve also snonux.de with the same Gemini server but for that SNI would be required as I have only one IP address. 

Cheers and sunny greetings!

Paul

**Comment by a-h** [comment]
Hi Paul!

Yes, that's right, the server supports SNI, it's just that there's (currently) no command line flags to use it from the CLI tool.

The reason for this is just because it would be complicated to do with CLI flags, because each domain (usually) needs to provide a unique cert and key file. However, you can make your own command line with your config embedded in it (hopefully) easily enough.

I'm trying to keep in the spirit of minimalism, but a toml config wouldn't be much effort for me to implement. Let me know if you think that would be valuable.

Before starting up, the Gemini command line creates a map (dictionary in other languages) from each domain it's going to serve, and the certificate it's going to use for it, to a Gemini `Handler` that serves the content for that domain.

The Gemini `Handlers` can be custom code, e.g. because it needs to access databases or make API calls, but the Gemini command line just uses the filesystem handler to read files from disk when a request comes in.

So it's just a case of building the map and passing it to the server. With all the CLI flags removed, there's not much left.

```go
package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"os"
	"time"

	"github.com/a-h/gemini"
)

type configuration struct {
	// Domain name, e.g. localhost.
	domain string
	// Certfile is the path to a server cerfificate file.
	certFile string
	// Keyfile is the path to a server key file.
	keyFile string
	// Path to Gemini content to serve.
	path string
}

func main() {
	config := []configuration{
		{
			domain:   "buetow.org",
			certFile: "./certs/buetow.cert",
			keyFile:  "./certs/buetow.key",
			path:     "./content/buetow",
		},
		{
			domain:   "snonux.de",
			certFile: "./certs/snonux.cert",
			keyFile:  "./certs/snonux.key",
			path:     "./content/snonux",
		},
	}
	port := 1965
	readTimeout := time.Second * 5
	writeTimeout := time.Second * 10

	// Load the config.
	domainToHandler := map[string]*gemini.DomainHandler{}

	for i := 0; i < len(config); i++ {
		c := config[i]
		h := gemini.FileSystemHandler(gemini.Dir(c.path))
		cert, err := tls.LoadX509KeyPair(c.certFile, c.keyFile)
		if err != nil {
			fmt.Printf("error: failed to load certificates for domain %q: %v\n", c.domain, err)
			os.Exit(1)
		}
		dh := gemini.NewDomainHandler(c.domain, cert, h)
		domainToHandler[c.domain] = dh
	}

	// Start the server.
	ctx := context.Background()
	server := gemini.NewServer(ctx, fmt.Sprintf(":%d", port), domainToHandler)
	server.ReadTimeout = readTimeout
	server.WriteTimeout = writeTimeout
	err := server.ListenAndServe()
	if err != nil {
		fmt.Printf("error: %v\n", err)
		os.Exit(1)
	}
}
```

**Comment by snonux** [comment]
Ah thanks, that makes sense! I will do it that way then!

**Comment by a-h** [comment]
Great! Consider this closed but feel free to reopen if you need a hand - I'm happy to help, and I'm glad you're enjoying the code. I enjoyed writing it, and I use it myself for my Gemini capsule.

I suspect there's not many folks that need to use the SNI support, so I've optimised the CLI for the simplest case, but if it's a popular request, I'll update the server CLI to support a TOML config to configure that instead of CLI flags.

**Comment by snonux** [comment]
I have done that, works as advertised :bow:

**Comment by thedeany** [comment]
Apologies in advance for necroing this thread, but I'm looking to do something similar and I'm not quite sure I understand how to proceed. I'm just dipping my toes into the Geminisphere at all for the first time. I'm looking to host a couple servers via a Docker container; do I have it correct that I would need to build my own image from source with the `cmd/main.go` updated to something like you posted above?

**Comment by a-h** [comment]
I've created a new release that allows you to use a TOML configuration file to set up multiple domains.

With that in place, the Dockerfile should be a simple case of using COPY to add the:

* gemini binary
* TOML configuration file
* Source gemini files
* Certificate files
* Key files

And then setting the entrypoint to the gemini executable. If you could give it a shot and let me know how that goes, that would be great. :)

**Comment by thedeany** [comment]
Alright, I think I've got it!

I updated the `serve-gemini.sh` script to add a `--config=$CONFIG` flag, built the Docker image, added a TOML file and pointed my `CONFIG` environment variable to that file path, and I appear to be up and running with some test domains. I'm not super familiar with TOML, and very much not familiar with Go, so it took me a bit to figure out the correct syntax for the TOML file. This seems to be working, but can you confirm this is the intended format? Or is there a simpler way to write this?

```toml
[Domain."mydomain.tld"]
Path = "/content/mydomain.tld"
CertFilePath = "/certs/mydomain.tld/server.crt"
KeyFilePath = "/certs/mydomain.tld/server.key"

[Domain."other.tld"]
Path = "/content/other.tld"
CertFilePath = "/certs/other.tld/server.crt"
KeyFilePath = "/certs/other.tld/server.key"
```

If this is all correct, I'd be more than happy to submit a PR with the changes and some documentation updates/examples.

**Comment by a-h** [comment]
That looks right to me!

I could update the toml config with something that means we don't have to write `[Domain."example.com"]` and could write `[Domain]` and have a specific line for `Name = example.com` though?

A PR would be lovely, if you have time.

**Comment by thedeany** [comment]
I think using `[Domain]` would be much cleaner. In fact, that's what I attempted to do at first but it obviously did not work.
